apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge
bases:
- https://github.com/jasonblanchard/k8s-pipeline-testing-notebook/deploy/edge?ref=f5d402f4ad8a80d7a607876d6e471318f6a22698 # {"$openapi":"base"}
images:
- name: jasonblanchard/k8s-pipeline-notebook
  newTag: "f5d402f4ad8a80d7a607876d6e471318f6a22698" # {"$openapi":"version"}
commonAnnotations:
  version: "f5d402f4ad8a80d7a607876d6e471318f6a22698" # {"$openapi":"version"}
resources:
- after.yaml
