apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
bases:
- https://github.com/jasonblanchard/k8s-pipeline-testing-notebook/deploy/production?ref=238bc31c88124a217ed30b4de1e00dade8c9ba27 # {"$openapi":"base"}
images:
- name: jasonblanchard/k8s-pipeline-notebook
  newTag: "238bc31c88124a217ed30b4de1e00dade8c9ba27" # {"$openapi":"version"}
commonAnnotations:
  version: "238bc31c88124a217ed30b4de1e00dade8c9ba27" # {"$openapi":"version"}
