apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
bases:
- https://github.com/jasonblanchard/k8s-pipeline-testing-notebook/deploy/production?ref=aa492b5bd0b1fcf3e002fefc0ed5d208ceef220f # {"$openapi":"base"}
images:
- name: jasonblanchard/k8s-pipeline-notebook
  newTag: "aa492b5bd0b1fcf3e002fefc0ed5d208ceef220f" # {"$openapi":"version"}
commonAnnotations:
  version: "aa492b5bd0b1fcf3e002fefc0ed5d208ceef220f" # {"$openapi":"version"}
