apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge
bases:
- https://github.com/jasonblanchard/k8s-pipeline-testing-notebook/deploy/edge?ref=e01b1d3c59ac1d93fc2b407ee190ffdf33288ad0 # {"$openapi":"base"}
images:
- name: jasonblanchard/k8s-pipeline-notebook
  newTag: "e01b1d3c59ac1d93fc2b407ee190ffdf33288ad0" # {"$openapi":"version"}
commonAnnotations:
  version: "e01b1d3c59ac1d93fc2b407ee190ffdf33288ad0" # {"$openapi":"version"}
