apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edge
bases:
- https://github.com/jasonblanchard/k8s-pipeline-testing-notebook/deploy/edge?ref=f736850828ec532640d7ae3797a42bb915718f43 # {"$openapi":"base"}
images:
- name: jasonblanchard/k8s-pipeline-notebook
  newTag: "f736850828ec532640d7ae3797a42bb915718f43" # {"$openapi":"version"}
commonAnnotations:
  version: "f736850828ec532640d7ae3797a42bb915718f43" # {"$openapi":"version"}
